name: CI
on: push

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          cd carriage-user-ios
          xcodebuild -scheme Pods-carriage-user-ios -workspace carriage-user-ios.xcworkspace -quiet clean build
